name: youtube-thumbnail-performance-predictor
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - easyocr
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy>=1.24.0,<2.0.0
  - pandas
  - pillow
  - scikit-learn
  - black
  - flake8
  - facenet_pytorch
  - isort
  - pytest
  - pip:
    - python-dotenv
    - deepface
    - tf-keras
    - opencv-python<4.9.0
    - sentence-transformers
    - -e .
