name: youtube-thumbnail-performance-predictor
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - easyocr
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pillow
  - scikit-learn
  - black
  - flake8
  - facenet_pytorch
  - isort
  - pytest
  - pip:
    - python-dotenv
    - -e .
